# Generated by Django 3.2.2 on 2023-07-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prcie',
            new_name='price',
        ),
    ]
